name: CI

on: ['push', 'pull_request']

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }} + ${{ matrix.symfony-version}})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SYMFONY_REQUIRE: "${{ matrix.symfony_require }}"
    strategy:
      matrix:
        include:
          - php: '7.4'
            symfony_require: '4.4.*'
          - php: '7.4'
            symfony_require: '5.4.*'
          - php: '8.1'
            symfony_require: '4.4.*'
          - php: '8.1'
            symfony_require: '5.4.*'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: pecl, composer
          extensions: curl, json, mbstring, openssl

      - name: Install Composer dependencies
        run: |
          composer install

      - name: Run unit tests
        run: |
          vendor/bin/phpunit
